### PR TITLE
Daskworker node management

### PR DESCRIPTION
**Pull request by EF-USAF**

### CODE REVIEW

**Comment by MM-USAF** [comment]
Should this be tested specifically on Azure?

**Comment by EF-USAF** [comment]
This PR is a general solution, the steps in the readme work everywhere

**Review by MM-USAF — APPROVED** [review]
I was able to spin this deployment up and use worker nodes in the dask notebook.

**Comment by DF-USAF** [comment]
I can spin up this deployment if I don't use more than one node. If I use two nodes then keycloak-postgress always switches to the second node. I'm not sure if that's supposed to happen but it doesn't work after that.

**Comment by EF-USAF** [comment]
@DF-USAF That doesn't seem right. Are you setting the taint/label before or after installing opal?

**Comment by DF-USAF** [comment]
@EF-USAF I'm not sure what that means, sorry. I'll be back at it on Monday and we'll figure it out.

**Review by DF-USAF — APPROVED** [review]
I finally got everything spun up. I didn't have any conda env working though, so I couldn't run any dask tasks to make sure this worked in the way I would like to.

**Pull request merged**
